UNIV_NUM_COLS = ["BOROUGH", "BLOCK", "LOT", "RESIDENTIAL UNITS",	"COMMERCIAL UNITS","TOTAL UNITS", "YEAR BUILT", "TAX CLASS AT TIME OF SALE", "LAND SQUARE FEET", "GROSS SQUARE FEET"]
UNIV_CAT_COLS = ["BUILDING CLASS CATEGORY", "TAX CLASS AT PRESENT", "BUILDING CLASS AT PRESENT"]

CUR_YEAR = 2024